FROM ubuntu
MAINTAINER JustZht <zhtsu47@me.com>

RUN echo yo here we begin

RUN echo yo apt-get
RUN apt-get update
RUN apt-get -qqy install apache2 

RUN echo yo newpath
VOLUME /usr/docker/startpage/
ADD . /usr/docker/startpage/

RUN chown -R www-data:www-data /usr/docker/startpage/
ADD apache_startpage.conf /etc/apache2/sites-enabled/000-default.conf

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/log/apache2/pid

RUN echo yo port 80 open
EXPOSE 80


CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]